/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestRouteImport } from './routes/test'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BracketUsernameRouteImport } from './routes/bracket/$username'
import { Route as ApiPredictionsIndexRouteImport } from './routes/api/predictions/index'
import { Route as ApiLeaderboardIndexRouteImport } from './routes/api/leaderboard/index'
import { Route as ApiPredictionsLockRouteImport } from './routes/api/predictions/lock'
import { Route as ApiOgUsernameRouteImport } from './routes/api/og.$username'
import { Route as ApiLeaderboardCalculateRouteImport } from './routes/api/leaderboard/calculate'
import { Route as ApiBracketUsernameRouteImport } from './routes/api/bracket/$username'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BracketUsernameRoute = BracketUsernameRouteImport.update({
  id: '/bracket/$username',
  path: '/bracket/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPredictionsIndexRoute = ApiPredictionsIndexRouteImport.update({
  id: '/api/predictions/',
  path: '/api/predictions/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLeaderboardIndexRoute = ApiLeaderboardIndexRouteImport.update({
  id: '/api/leaderboard/',
  path: '/api/leaderboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPredictionsLockRoute = ApiPredictionsLockRouteImport.update({
  id: '/api/predictions/lock',
  path: '/api/predictions/lock',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgUsernameRoute = ApiOgUsernameRouteImport.update({
  id: '/api/og/$username',
  path: '/api/og/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLeaderboardCalculateRoute = ApiLeaderboardCalculateRouteImport.update({
  id: '/api/leaderboard/calculate',
  path: '/api/leaderboard/calculate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBracketUsernameRoute = ApiBracketUsernameRouteImport.update({
  id: '/api/bracket/$username',
  path: '/api/bracket/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/test': typeof TestRoute
  '/bracket/$username': typeof BracketUsernameRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/bracket/$username': typeof ApiBracketUsernameRoute
  '/api/leaderboard/calculate': typeof ApiLeaderboardCalculateRoute
  '/api/og/$username': typeof ApiOgUsernameRoute
  '/api/predictions/lock': typeof ApiPredictionsLockRoute
  '/api/leaderboard': typeof ApiLeaderboardIndexRoute
  '/api/predictions': typeof ApiPredictionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/test': typeof TestRoute
  '/bracket/$username': typeof BracketUsernameRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/bracket/$username': typeof ApiBracketUsernameRoute
  '/api/leaderboard/calculate': typeof ApiLeaderboardCalculateRoute
  '/api/og/$username': typeof ApiOgUsernameRoute
  '/api/predictions/lock': typeof ApiPredictionsLockRoute
  '/api/leaderboard': typeof ApiLeaderboardIndexRoute
  '/api/predictions': typeof ApiPredictionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/test': typeof TestRoute
  '/bracket/$username': typeof BracketUsernameRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/bracket/$username': typeof ApiBracketUsernameRoute
  '/api/leaderboard/calculate': typeof ApiLeaderboardCalculateRoute
  '/api/og/$username': typeof ApiOgUsernameRoute
  '/api/predictions/lock': typeof ApiPredictionsLockRoute
  '/api/leaderboard/': typeof ApiLeaderboardIndexRoute
  '/api/predictions/': typeof ApiPredictionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/test'
    | '/bracket/$username'
    | '/api/auth/$'
    | '/api/bracket/$username'
    | '/api/leaderboard/calculate'
    | '/api/og/$username'
    | '/api/predictions/lock'
    | '/api/leaderboard'
    | '/api/predictions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/test'
    | '/bracket/$username'
    | '/api/auth/$'
    | '/api/bracket/$username'
    | '/api/leaderboard/calculate'
    | '/api/og/$username'
    | '/api/predictions/lock'
    | '/api/leaderboard'
    | '/api/predictions'
  id:
    | '__root__'
    | '/'
    | '/test'
    | '/bracket/$username'
    | '/api/auth/$'
    | '/api/bracket/$username'
    | '/api/leaderboard/calculate'
    | '/api/og/$username'
    | '/api/predictions/lock'
    | '/api/leaderboard/'
    | '/api/predictions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TestRoute: typeof TestRoute
  BracketUsernameRoute: typeof BracketUsernameRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiBracketUsernameRoute: typeof ApiBracketUsernameRoute
  ApiLeaderboardCalculateRoute: typeof ApiLeaderboardCalculateRoute
  ApiOgUsernameRoute: typeof ApiOgUsernameRoute
  ApiPredictionsLockRoute: typeof ApiPredictionsLockRoute
  ApiLeaderboardIndexRoute: typeof ApiLeaderboardIndexRoute
  ApiPredictionsIndexRoute: typeof ApiPredictionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bracket/$username': {
      id: '/bracket/$username'
      path: '/bracket/$username'
      fullPath: '/bracket/$username'
      preLoaderRoute: typeof BracketUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/predictions/': {
      id: '/api/predictions/'
      path: '/api/predictions'
      fullPath: '/api/predictions'
      preLoaderRoute: typeof ApiPredictionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/leaderboard/': {
      id: '/api/leaderboard/'
      path: '/api/leaderboard'
      fullPath: '/api/leaderboard'
      preLoaderRoute: typeof ApiLeaderboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/predictions/lock': {
      id: '/api/predictions/lock'
      path: '/api/predictions/lock'
      fullPath: '/api/predictions/lock'
      preLoaderRoute: typeof ApiPredictionsLockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og/$username': {
      id: '/api/og/$username'
      path: '/api/og/$username'
      fullPath: '/api/og/$username'
      preLoaderRoute: typeof ApiOgUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/leaderboard/calculate': {
      id: '/api/leaderboard/calculate'
      path: '/api/leaderboard/calculate'
      fullPath: '/api/leaderboard/calculate'
      preLoaderRoute: typeof ApiLeaderboardCalculateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bracket/$username': {
      id: '/api/bracket/$username'
      path: '/api/bracket/$username'
      fullPath: '/api/bracket/$username'
      preLoaderRoute: typeof ApiBracketUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TestRoute: TestRoute,
  BracketUsernameRoute: BracketUsernameRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiBracketUsernameRoute: ApiBracketUsernameRoute,
  ApiLeaderboardCalculateRoute: ApiLeaderboardCalculateRoute,
  ApiOgUsernameRoute: ApiOgUsernameRoute,
  ApiPredictionsLockRoute: ApiPredictionsLockRoute,
  ApiLeaderboardIndexRoute: ApiLeaderboardIndexRoute,
  ApiPredictionsIndexRoute: ApiPredictionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
